# Usa la imagen oficial de Python (versión slim)
FROM python:3.11-slim-buster

# Instala dependencias del sistema necesarias para conectarse a SQL Server
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg2 \
        wget \
        apt-transport-https \
        software-properties-common \
        unixodbc-dev \
        curl && \
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requerimientos e instala las dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación
COPY . .

# Configura las variables de entorno para Flask
ENV FLASK_APP=app.py
ENV FLASK_DEBUG=1
ENV FLASK_RUN_PORT=5003

# Expone el puerto en el que correrá la aplicación
EXPOSE 5003

# Comando para iniciar la aplicación
CMD ["flask", "run", "--host=0.0.0.0"]
